package greeter;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    
    public static void main(String[] args) {
    	System.out.println(
    			GreetingFormatter.greetings(args[0]) );
    }
}
